pipeline {
    agent any

    environment {
        DOCKER_BUILDKIT = 1
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/lucashard/TestExam'
            }
        }
        stage('Build Docker Image') {
            steps {
                sh 'docker build -t testexam_app -f TestExam/Dockerfile .'
            }
        }
        stage('Run Container') {
            steps {
                sh 'docker stop testexam_app || true'
                sh 'docker rm testexam_app || true'
                sh 'docker run -d --name testexam_app -p 8080:8080 testexam_app'
            }
        }
    }
}
